root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ./cmd"
bin = "./tmp/main"
include_ext = ["go", "html", "css", "js", "jpg", "jpeg", "png", "gif", "svg", "ico", "ttf", "woff", "woff2"]
include_dir = ["cmd", "pkg", "templates", "static"]
exclude_dir = ["tmp", "vendor", "node_modules", ".git", ".github"]
delay = 1000
stop_on_error = true

[log]
time = false

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true