services:
  go-app:
    build: .
    restart: unless-stopped
    networks:
      - app-network
    expose:
      - "8000"

  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy_data:/data
      - ./Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - go-app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  caddy_data:
